In [1]:
import numpy as np
import pandas as pd
import pandas_datareader as pdr

In [2]:
df1 = pdr.DataReader('HCLTECH.NS',data_source='yahoo',start='2010-01-01',end='2020-01-01')
df1['Company Name'] = 'HCL'
df1

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,93.750000,92.012497,93.562500,92.775002,1632148.0,73.478745,HCL
2010-01-05,95.250000,92.637497,93.125000,94.862503,5037896.0,75.132080,HCL
2010-01-06,95.724998,91.250000,95.025002,92.000000,3992320.0,72.864944,HCL
2010-01-07,92.974998,89.800003,92.974998,90.037498,3665940.0,71.310638,HCL
2010-01-08,90.750000,87.312500,90.750000,87.937500,6241492.0,69.647415,HCL
...,...,...,...,...,...,...,...
2019-12-26,565.000000,559.549988,561.650024,560.500000,1848547.0,517.940979,HCL
2019-12-27,569.000000,557.000000,562.950012,567.549988,2786795.0,524.455505,HCL
2019-12-30,577.500000,564.250000,567.000000,569.299988,1800754.0,526.072693,HCL
2019-12-31,571.500000,565.049988,569.099976,568.099976,1838808.0,524.963806,HCL
2020-01-01,572.900024,566.849976,569.400024,571.950012,918373.0,528.521484,HCL

In [3]:
df2 = pdr.DataReader('M&M.NS',data_source='yahoo',start='2010-01-01',end='2020-01-01')
df2['Company Name'] = 'M&M'
df2

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,284.500000,271.375000,271.375000,282.462494,3739348.0,256.731750,M&M
2010-01-05,294.000000,280.250000,283.750000,287.662506,5197364.0,261.458038,M&M
2010-01-06,296.725006,288.075012,289.924988,294.562500,6827232.0,267.729523,M&M
2010-01-07,296.112488,285.287506,295.750000,288.950012,3304396.0,262.628265,M&M
2010-01-08,291.500000,286.637512,291.250000,288.975006,2527272.0,262.651031,M&M
...,...,...,...,...,...,...,...
2019-12-26,536.200012,527.049988,530.000000,528.349976,4623580.0,514.968323,M&M
2019-12-27,532.750000,525.049988,529.900024,530.150024,3017840.0,516.722778,M&M
2019-12-30,539.849976,531.349976,531.349976,536.900024,4697710.0,523.301880,M&M
2019-12-31,538.650024,530.599976,538.650024,531.549988,2502181.0,518.087341,M&M
2020-01-01,538.000000,529.549988,532.900024,536.599976,2611808.0,523.009399,M&M

In [4]:
df3 = pdr.DataReader('TATAMOTORS.BO',data_source='yahoo',start='2010-01-01',end='2020-01-01')
df3['Company Name'] = 'TATAMOTORS'
df3

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,164.292068,155.931534,156.525177,163.728104,6715949.0,153.321976,TATAMOTORS
2010-01-05,166.617203,159.908966,165.232010,160.472946,5865107.0,150.273697,TATAMOTORS
2010-01-06,162.857422,159.305435,162.243988,160.700500,3534584.0,150.486801,TATAMOTORS
2010-01-07,162.065887,154.388046,161.244675,155.288406,5220538.0,145.418701,TATAMOTORS
2010-01-08,159.275742,155.159790,155.733643,156.159103,3700723.0,146.234039,TATAMOTORS
...,...,...,...,...,...,...,...
2019-12-26,176.350006,174.100006,176.000000,174.600006,714360.0,174.600006,TATAMOTORS
2019-12-27,176.949997,174.949997,175.500000,176.100006,500007.0,176.100006,TATAMOTORS
2019-12-30,184.250000,176.449997,177.500000,183.600006,1976823.0,183.600006,TATAMOTORS
2019-12-31,187.899994,181.550003,184.100006,185.100006,2633656.0,185.100006,TATAMOTORS
2020-01-01,186.699997,183.750000,185.850006,184.399994,1461450.0,184.399994,TATAMOTORS

In [5]:
df4 = pdr.DataReader('HDFCBANK.NS',data_source='yahoo',start='2010-01-01',end='2020-01-01')
df4['Company Name'] = 'HDFCBANK'
df4

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,172.850006,169.255005,170.000000,170.570007,3050490.0,155.755508,HDFCBANK
2010-01-05,172.500000,170.500000,171.000000,170.720001,8386600.0,155.892471,HDFCBANK
2010-01-06,172.000000,168.809998,171.399994,170.835007,6639840.0,155.997513,HDFCBANK
2010-01-07,176.839996,170.160004,176.839996,171.279999,6123980.0,156.403839,HDFCBANK
2010-01-08,172.339996,170.100006,171.199997,171.505005,7085900.0,156.609314,HDFCBANK
...,...,...,...,...,...,...,...
2019-12-26,1291.849976,1264.650024,1289.699951,1270.449951,7474879.0,1250.436279,HDFCBANK
2019-12-27,1279.000000,1270.000000,1272.000000,1275.000000,3546496.0,1254.914673,HDFCBANK
2019-12-30,1288.750000,1274.050049,1282.000000,1282.150024,4667095.0,1261.952026,HDFCBANK
2019-12-31,1281.949951,1268.650024,1281.949951,1272.099976,4178528.0,1252.060303,HDFCBANK
2020-01-01,1280.000000,1270.599976,1276.099976,1278.599976,1836849.0,1258.457886,HDFCBANK

In [6]:
df5 = pdr.DataReader('RELIANCE.NS',data_source='yahoo',start='2010-01-01',end='2020-01-01')
df5['Company Name'] = 'RELIANCE'
df5

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,540.427307,506.127411,540.427307,532.700500,35372156.0,484.266083,RELIANCE
2010-01-05,569.551208,527.697937,569.551208,530.323059,9872785.0,482.104767,RELIANCE
2010-01-06,542.111328,530.298279,534.879883,538.891846,10933743.0,489.894623,RELIANCE
2010-01-07,552.265076,533.938782,538.891846,547.832092,12090336.0,498.021820,RELIANCE
2010-01-08,551.670715,542.854309,548.797974,546.395691,6973331.0,496.716125,RELIANCE
...,...,...,...,...,...,...,...
2019-12-26,1538.367798,1495.969727,1527.173950,1501.170410,13734705.0,1490.759155,RELIANCE
2019-12-27,1531.681152,1507.015015,1512.661499,1527.867310,8158196.0,1517.270874,RELIANCE
2019-12-30,1533.117554,1513.701660,1531.433594,1529.699951,7902607.0,1519.090820,RELIANCE
2019-12-31,1529.204712,1493.889404,1527.520630,1499.833130,10246683.0,1489.431274,RELIANCE
2020-01-01,1512.760498,1491.363403,1503.745972,1495.424927,6463060.0,1485.053467,RELIANCE

In [7]:
data = pd.concat([df1,df2,df3,df4,df5])

In [8]:
data

,High,Low,Open,Close,Volume,Adj Close,Company Name
Date,,,,,,,
2010-01-04,93.750000,92.012497,93.562500,92.775002,1632148.0,73.478745,HCL
2010-01-05,95.250000,92.637497,93.125000,94.862503,5037896.0,75.132080,HCL
2010-01-06,95.724998,91.250000,95.025002,92.000000,3992320.0,72.864944,HCL
2010-01-07,92.974998,89.800003,92.974998,90.037498,3665940.0,71.310638,HCL
2010-01-08,90.750000,87.312500,90.750000,87.937500,6241492.0,69.647415,HCL
...,...,...,...,...,...,...,...
2019-12-26,1538.367798,1495.969727,1527.173950,1501.170410,13734705.0,1490.759155,RELIANCE
2019-12-27,1531.681152,1507.015015,1512.661499,1527.867310,8158196.0,1517.270874,RELIANCE
2019-12-30,1533.117554,1513.701660,1531.433594,1529.699951,7902607.0,1519.090820,RELIANCE
2019-12-31,1529.204712,1493.889404,1527.520630,1499.833130,10246683.0,1489.431274,RELIANCE
2020-01-01,1512.760498,1491.363403,1503.745972,1495.424927,6463060.0,1485.053467,RELIANCE

In [9]:
data.to_csv('dataset/stock_data.csv')